### ISSUE TITLE
Azure extensions are preventing deployment 

### ISSUE THREAD

**Issue by alfredodeza** [education/codespaces-project-template-js#13]
While trying to deploy the application, I get errors when selecting "Azure Static Web Apps" after signing into Azure. The following error shows up:

 ```
6:55:22 PM: Error: Converting circular structure to JSON
    --> starting at object with constructor 'AzureAccountTreeItem'
    |     property '_cachedChildren' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'SubscriptionTreeItem'
    --- property 'parent' closes the circle
```
Changing the Azure Tools extension to the previous version prevents the error from happening. 

Potential solution: pin to the previous version in `devcontainer.json` in the `settings` section

**Comment by saragibby** [comment]
Thanks for spotting this @alfredodeza! At what point in the deploy process did you get this error? I have not received that error on the different Azure accounts I've tested, so super curious to learn more. 

I tried pinning the version for the extensions, link you have in your PR, but when I started up a new Codespace from that config it immediately auto-updated the extensions and told me a reload was required. Did you have to also turn the auto-update off to get the deploy to work?

**Comment by saragibby** [comment]
Thanks for the info @alfredodeza! This is a pretty out of the box deployment to Static Web Apps within a Codespace, so if it isn't working for you it could possibly mean there is a bug that will impact SWA deployment within any Codespace. Be good to see if we can work with @softchris to get this feedback to the SWA team, and get their recommendations how to proceed.

**Comment by saragibby** [comment]
@alfredodeza are you still unable to deploy to Azure Static Web Apps from within this Codespace? I amill unable to reproduce this error. It would be helpful to learn more and have screen shots if you are still hitting it, if not we should close this one up. Thanks!

**Comment by alfredodeza** [comment]
It is probably a good idea to close this until we are able to reproduce
