### ISSUE TITLE
GitHub Pages site appears blank after following tutorial

### ISSUE THREAD

**Issue by alexfrnn** [education/codespaces-project-template-js#147]
![image](https://github.com/user-attachments/assets/5e23f06a-51be-423d-a077-68ff16d276e4)

Description:
I followed the steps in the tutorial to deploy my portfolio using GitHub Pages, but the site appears blank. I am not sure how to resolve this issue. The repository is based on the Codespaces template for creating and deploying a portfolio ([github-education-resources/codespaces-project-template-js](https://github.com/github-education-resources/codespaces-project-template-js)).

**Comment by anibue** [comment]
+1

**Comment by alexfrnn** [comment]
I managed to solve the problem
