### ISSUE TITLE
How do I change the font for the name?

### ISSUE THREAD

**Issue by RadioactivePotato** [education/codespaces-project-template-js#26]
![image](https://user-images.githubusercontent.com/75719839/213283120-45e06d79-93e0-40bb-a4bb-f0868f84e39f.png)

**Comment by saragibby** [comment]
Hi @RadioactivePotato! There are 2 places this projects defines `font-family` in CSS. The first in the styles for `html, body` at [line 13](https://github.com/education/codespaces-project-template-js/blob/0bec1dafead8bb91365fe343b0252c0989104605/src/styles.css#L13). But, to get to your question, the `h1` element overrides that `font-family` set for `html, body` on [styles.css line 51](https://github.com/education/codespaces-project-template-js/blob/0bec1dafead8bb91365fe343b0252c0989104605/src/styles.css#L51). That is where you need to update to a `font-family` you'd like your name to display in. 

These font types are imported in [styles.css line 5](https://github.com/education/codespaces-project-template-js/blob/0bec1dafead8bb91365fe343b0252c0989104605/src/styles.css#L5). If you'd like to import and use a different font, locate the font you'd like and import it in a similar way and you should then be able to use it. 

Hope that helps! I'm going to close this issue, but feel free to add comments with your questions, or open up a new issue as you find other items. Thanks!
