### ISSUE TITLE
Repository Token is invalid (Deployment with Azure Static Web Apps)

### ISSUE THREAD

**Issue by linuskhl** [education/codespaces-project-template-js#42]
When I do the deployment via Azure Static Web Apps, everything works fine until 4.iv. But when I send I get the following error message:

> RepositoryToken is invalid. Provided token has invalid permissions and cannot be used to setup Github Action CI/CD. Admin rights are required for the repository.

What are some possible steps to fix this problem, or where can I find more resources to help me fix this issue?

**Comment by v3gaaa** [comment]
I have the same problem, any updates on the solution?

**Comment by linuskhl** [comment]
Hey @v3gaaa,

I have found a way to complete the technical onboarding
