### ISSUE TITLE
Grammatical error in README.md

### ISSUE THREAD

**Issue by mohammadshaad** [education/codespaces-project-template-js#45]
Hello! I noticed a grammatical error in the readme.md file that needs to be corrected. The word "complete" should be changed to "completed." I would be happy to make the necessary modifications, so please assign me this issue. Thank you!

![Screen Shot 2023-05-09 at 3 08 26 PM](https://user-images.githubusercontent.com/89409389/237057556-095d0e73-5b66-454c-a2c8-506d68304d53.png)

**Comment by geoffreylgv** [comment]
This issue is completed, and should be closed.
