### ISSUE TITLE
Spanish Localization: review and update

### ISSUE THREAD

**Issue by cyz** [education/codespaces-project-template-js#48]
Hi all 👋

We need review the existing Spanish translation and make sure it is working according to the English content.

Main folder: [https://github.com/education/codespaces-project-template-js](https://github.com/education/codespaces-project-template-js)

**Please compare each file below to its original in English and if required, please send a PR.**
| File | Status         |
|------|----------------|
| README.md     | pending review |
| slides.pptx   | pending review |

The localized version should be in the [`translations/es`](https://github.com/education/codespaces-project-template-js) folder. After your review, if you find that there is no need to submit a pull request with file changes, please comment on this issue with the status **DONE** for each file.

**Comment by cyz** [comment]
@AnahiSU

**Comment by AnahiSU** [comment]
Hola @cyz, ya estoy terminando la actualización del repositorio, hoy mismo mando el push

**Comment by glaucia86** [comment]
@cyz I made a code review and LGTM for me #55
