### ISSUE TITLE
Brazilian Portuguese: review and update

### ISSUE THREAD

**Issue by cyz** [education/codespaces-project-template-js#49]
Hi all 👋

We need review the existing Brazilian Portuguese translation and make sure it is working according to the English content.

Main folder: [https://github.com/education/codespaces-project-template-js](https://github.com/education/codespaces-project-template-js)

**Please compare each file below to its original in English and if required, please send a PR.**
| File | Status         |
|------|----------------|
| README.md     | pending review |
| slides.pptx   | pending review |

The localized version should be in the [`translations/pt-BR`](https://github.com/education/codespaces-project-template-js) folder. After your review, if you find that there is no need to submit a pull request with file changes, please comment on this issue with the status **DONE** for each file.

**Comment by WirelessLife** [comment]
The existing Brazilian Portuguese translation needs to be updated to include the new Copilot section added to the repo. We should also create Brazilian Portuguese translations of the videos as well.
