### ISSUE TITLE
I do not have an active Azure subscription.

### ISSUE THREAD

**Issue by SusanSuarez** [education/codespaces-project-template-js#51]
![imagen](https://github.com/education/codespaces-project-template-js/assets/88943965/69ae770d-87f4-4a57-8094-30043a3f6a02)
![imagen](https://github.com/education/codespaces-project-template-js/assets/88943965/7a3c94cc-d4fe-4946-bce3-3aa7295d3539)
No tengo acceso a AZure

**Comment by saragibby** [comment]
Yes, it sounds like the issue may be that you do not have an active Azure subscription. Your best bet will be to follow the prompts in Azure portal to ensure you have an active Azure subscription you can deploy to. 

Here is a couple additional links to help:
https://azure.microsoft.com/free/
https://azure.microsoft.com/en-us/get-started/

I will close this issue, but please feel free to start a Discussion if you have any additional questions or issues deploying your site.
